### PR TITLE
Clean up event, plus hooking in missing providers from controllers

### PR DESCRIPTION
**Pull request by swilla**

### CODE REVIEW

**Comment by swilla** [comment]
Add the trigger for post_user_login so any login events are run after successful login

**Comment by swilla** [comment]
Do you want me to resubmit this pull request with the latest version of the social module? I think the clean up event is pretty helpful especially when you are testing functionality and users are deleted and recreated multiple times. If the user information is in the authentications table their will be errors when trying to link accounts.

**Comment by philsturgeon** [comment]
Hey @swilla. Sorry man, I didnt notice this module was getting pull requests. Can you clean up and reimplement this if it needs to be done?

**Comment by swilla** [comment]
I sent another pull request on the new version.

**Pull request closed without merging**
